""" Generated thies list with the help of ChatGPT - I want to use it to calculate the algorithmus, as well as to filter for tags"""

poi_tags = {
    # 1️⃣ Food & Drink 🍽️🍹 (1-20)
    1: "Restaurant",
    2: "Cafe",
    3: "Bar",
    4: "Pub",
    5: "Bakery",
    6: "Ice Cream Shop",
    7: "Snack Bar",
    8: "Food Truck",
    9: "Winery",
    10: "Brewery",
    11: "Tea House",
    12: "Cocktail Bar",
    13: "Beer Garden",
    14: "Supermarket",
    15: "Market",
    16: "Organic Store",
    17: "Grocery Store",
    18: "Deli",
    19: "Farmers' Market",
    20: "Butcher Shop",

    # 2️⃣ Shopping & Commerce 🛍️🏦 (21-35)
    21: "Bookstore",
    22: "Clothing Store",
    23: "Shoe Store",
    24: "Electronics Store",
    25: "Furniture Store",
    26: "Second-Hand Store",
    27: "Shopping Center",
    28: "Jewelry Store",
    29: "Art Gallery",
    30: "Pharmacy",
    31: "Toy Store",
    32: "Department Store",
    33: "Florist",
    34: "Pet Store",
    35: "Hardware Store",

    # 3️⃣ Entertainment & Culture 🎭🎶 (36-55)
    36: "Cinema",
    37: "Theater",
    38: "Museum",
    39: "Concert Hall",
    40: "Opera",
    41: "Comedy Club",
    42: "Karaoke Bar",
    43: "Escape Room",
    44: "Casino",
    45: "Amusement Park",
    46: "Zoo",
    47: "Aquarium",
    48: "Planetarium",
    49: "Arcade",
    50: "Bowling Alley",
    51: "Stadium",
    52: "Sports Field",
    53: "Skatepark",
    54: "Playground",
    55: "Climbing Hall",

    # 4️⃣ Nature & Outdoor 🌿🏞️ (56-75)
    56: "Park",
    57: "Botanical Garden",
    58: "Beach",
    59: "Lake",
    60: "River",
    61: "Mountain",
    62: "Forest",
    63: "Cave",
    64: "Waterfall",
    65: "Glacier",
    66: "Desert",
    67: "National Park",
    68: "Nature Reserve",
    69: "Island",
    70: "Clearing",
    71: "Vineyard",
    72: "Windmill",
    73: "Lighthouse",
    74: "Observation Deck",
    75: "Ruins",

    # 5️⃣ Infrastructure & Public Services 🏛️🚉 (76-100)
    76: "Monument",
    77: "Church",
    78: "Temple",
    79: "Mosque",
    80: "Synagogue",
    81: "Library",
    82: "Co-Working Space",
    83: "University",
    84: "School",
    85: "Hospital",
    86: "Medical Center",
    87: "Fire Station",
    88: "Police Station",
    89: "Bank",
    90: "Train Station",
    91: "Airport",
    92: "Bus Stop",
    93: "Car Rental",
    94: "Hotel",
    95: "Hostel",
    96: "Campground",
    97: "Port",
    98: "Bridge",
    99: "Tunnel",
    100: "Town Hall"
}

""" Why count? - I want to add an outlieers function, here is my idea:
           The tag numbers of all interactions and creations of sights of one user is stored in their alg_str
           Than I can calculate the mean of these interaction points. When I have the mean value, I want to 
           propose a variety of tags around the mean for the user on the main page as well as the "outlieers" 
           which are random tags across the tag scheme. Evertime this outlieer is triggered, the algorithmus 
           will focus on this interaction and will weight it differently, than the others. With this thechnology
           I asure, that the user can see new stuff and stays active at the platform."""